### ISSUE TITLE
my loss became bigger and bigger

### ISSUE THREAD

**Issue by ClownW** [rdenadai/snakeplissken#4]
During my training, I found that my loss became bigger and bigger. However, when I check your source code, I found that it's MSE loss. So does this mean that my training didn't take effect.

**Comment by rdenadai** [comment]
Are you running with default parameters??? There's lot's of parameters one can change to run the game... also, did you try the default model to see if it's running ok for you???

**Comment by ClownW** [comment]
Well, I have changed your network to a small one. Also, the way the snake choose action, I changed it to choose action randomly according to the probability got from the normalized network output, because i  found that if the apple position didn't change after some time, the snake would turns around and never eat the apple. So I want the snake to do something differently in the same state to break its circle. 
 
Would this be the reason why my loss became bigger and bigger?

**Comment by rdenadai** [comment]
Could be... one important thing to notice is that it will go bigger until the snake learn a lot of the iterations from its state space (which is huge).
You could notice that if you run main.py for a period and the run train.py for much longer iterations (like 200k) the loss function will slow going down...

**Comment by ClownW** [comment]
您的来信已收到，祝您生活愉快！
